"""empty message

Revision ID: 111c6fbe933d
Revises: 
Create Date: 2020-06-19 13:48:33.677133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '111c6fbe933d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.String(length=25), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('record')
    # ### end Alembic commands ###
