"""empty message

Revision ID: 481f40baa097
Revises: 
Create Date: 2020-06-18 21:33:19.851304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '481f40baa097'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('maxplayers', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game')
    # ### end Alembic commands ###
